ALTER TABLE products ADD COLUMN IF NOT EXISTS colors JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS badge_keys JSON;
ALTER TABLE handyman_profiles ADD COLUMN IF NOT EXISTS badge_keys JSON;
ALTER TABLE handyman_profiles ADD COLUMN IF NOT EXISTS safety_rating NUMERIC(3,2) NOT NULL DEFAULT 0;
